## 판다스 자료구조

In [5]:
import pandas as pd
import numpy as np

### 1. Series 
- 1차원 데이터

In [3]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
type(obj)

pandas.core.series.Series

In [7]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj.values # series 데이타에서 values 속성을 얻어왔을 때 ndarray임을 알 수 있음

array([ 4,  7, -5,  3])

In [10]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [12]:
obj2.values

array([ 4,  7, -5,  3])

In [13]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [14]:
obj[0]

4

In [15]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2['d']

4

In [17]:
obj2[0]

4

In [18]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    4
dtype: int64

In [19]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [20]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [21]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [22]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [24]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [25]:
'd' in obj2

True

In [26]:
'e' in obj2

False

In [27]:
sdata = {'Ohio':3500, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

obj3 = pd.Series(sdata)
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
pd.isnull(obj4) # obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [32]:
obj4.name = "population"

In [33]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj4.index.name = "state"

In [36]:
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [37]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [38]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### 실습

* 딕셔너리-> 시리즈 변환 (index, values 출력)

In [40]:
dict_data = {'a': 1, 'b': 2, 'c': 3}

In [41]:
sr = pd.Series(dict_data)
sr

a    1
b    2
c    3
dtype: int64

In [43]:
sr.index

Index(['a', 'b', 'c'], dtype='object')

In [44]:
sr.values

array([1, 2, 3])

* 리스트 -> 시리즈 변환 (index, values 출력)

In [45]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

In [46]:
sr = pd.Series(list_data)
sr

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object

In [47]:
sr.index

RangeIndex(start=0, stop=5, step=1)

In [48]:
sr.values

array(['2019-01-02', 3.14, 'ABC', 100, True], dtype=object)

* 튜플 -> 시리즈 변환 (index, values 출력)

In [49]:
tup_data = ('영인', '2010-05-01', '여', True)

In [50]:
sr = pd.Series(tup_data)
sr

0            영인
1    2010-05-01
2             여
3          True
dtype: object

In [51]:
sr.index

RangeIndex(start=0, stop=4, step=1)

In [52]:
sr.values

array(['영인', '2010-05-01', '여', True], dtype=object)

* 튜플 -> 시리즈 변환 (index 설정)

In [54]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [55]:
sr = pd.Series(tup_data, index = index_name)
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [56]:
sr.index

Index(['이름', '생년월일', '성별', '학생여부'], dtype='object')

In [57]:
sr.values

array(['영인', '2010-05-01', '여', True], dtype=object)

* 시리즈 원소 선택

In [ ]:
tup_data = ('영인', '2010-05-01', '여', True)
index_name=['이름', '생년월일', '성별', '학생여부']

In [58]:
sr = pd.Series(tup_data, index=index_name)
sr

이름              영인
생년월일    2010-05-01
성별               여
학생여부          True
dtype: object

In [ ]:
# 색인을 통해 '영인' 값 얻어오기

In [59]:
sr['이름']

'영인'

In [60]:
sr[0]

'영인'

In [ ]:
# 색인(슬라이싱)을 통해 ''2010-05-01'과 '여' 선택하기

In [61]:
sr[['생년월일', '성별']]

생년월일    2010-05-01
성별               여
dtype: object

In [62]:
sr[[1, 2]]

생년월일    2010-05-01
성별               여
dtype: object

In [63]:
sr['생년월일':'성별']

생년월일    2010-05-01
성별               여
dtype: object

In [64]:
sr[1:3]

생년월일    2010-05-01
성별               여
dtype: object

### 2. DataFrame 
- 2차원 데이터

In [65]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)        
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [66]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [67]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [68]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [71]:
frame.head(6)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [72]:
pd.DataFrame(data, columns=["year", "state", "pop"])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [73]:
pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [74]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"],
             index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [75]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [76]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [77]:
# 열색인
frame2["state"]

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [83]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [78]:
type(frame2["state"])

pandas.core.series.Series

In [82]:
# 행색인
frame2.loc["one"]

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [84]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [85]:
frame2["one": "two"] # 슬라이싱으로 행을 가져올때는 loc를 안써도 추출이됨

     year state  pop debt
one  2000  Ohio  1.5  NaN
two  2001  Ohio  1.7  NaN

In [86]:
frame2.loc["one": "two"]

     year state  pop debt
one  2000  Ohio  1.5  NaN
two  2001  Ohio  1.7  NaN

In [87]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [88]:
frame2["debt"] = 16.5
frame2

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [89]:
frame2["debt"] = np.arange(6)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [92]:
sr = pd.Series([1, 3,  5], index=["one", "three", "five"])
frame2["debt"] = sr
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   1.0
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   3.0
four   2001  Nevada  2.4   NaN
five   2002  Nevada  2.9   5.0
six    2003  Nevada  3.2   NaN

In [93]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [94]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [95]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [96]:
frame3.name = "population"
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [97]:
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

### 3. Index 
- 행과 열을 알려주는 메타 데이터

In [98]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
obj

a    0
b    1
c    2
dtype: int64

In [99]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [100]:
obj.index[:2]

Index(['a', 'b'], dtype='object')

In [102]:
obj.index[1] = 'd'

TypeError: ignored

In [104]:
labels = pd.Index(np.arange(3))

pd.Series([1, 2, 3], index=labels)

0    1
1    2
2    3
dtype: int64

### 실습

* 딕셔너리->데이터프레임 변환

In [106]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}

In [107]:
df = pd.DataFrame(dict_data)
df

   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

* 행인덱스/ 열 이름 설정

In [108]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 준서, 예은 -> '학생1', '학생2'

In [109]:
df.index = ['학생1', '학생2']
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 나이, 성별, 학교 -> '연령', '남녀', '소속'

In [110]:
df.columns = ['연령', '남녀', '소속']
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [ ]:
# 행인덱스/ 열 이름 변경
# rename 사용하여 변경

In [114]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [115]:
df.rename(index ={"준서":"학생1", "예은":"학생2"}, inplace=True)
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [116]:
df.rename(columns = {"나이":"연령", "성별":"남녀", "학교":"소속"}, inplace=True)
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [117]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']], 
                   index=['준서', '예은'],
                   columns=['나이', '성별', '학교'])

df.rename(columns={'나이':'연령', '성별':'남녀', '학교':'소속'},
         index={'준서':'학생1', '예은':'학생2'}, inplace=True)
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

## 중요한 기능들

### 1. 재색인

In [130]:
sr = pd.Series([1, 2, 3, 4], index=[0, 3, 4, 5])
sr

0    1
3    2
4    3
5    4
dtype: int64

In [133]:
sr.reindex(np.arange(6), method='bfill')

0    1
1    2
2    2
3    2
4    3
5    4
dtype: int64

### 2. 로우나 컬럼 삭제하기

In [134]:
obj = pd.Series(np.arange(5), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [135]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int64

In [136]:
obj.drop(['c', 'd'])

a    0
b    1
e    4
dtype: int64

In [138]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [141]:
# axis=0(행축), axis=1(열축)
# drop 연산을 할경우 : 지정된 축을 삭제

# data.drop('Colorado', axis=0) # 행축을 삭제
data.drop('Colorado', axis="index") # 행축을 삭제

          one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [143]:
# data.drop("two", axis=1)
data.drop("two", axis="columns")

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [144]:
data.drop(["two", "four"], axis="columns")

          one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### 3. 색인하기, 선택하기, 거르기

In [145]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
            index = ['Ohio', 'Colorado', 'Utah', 'New York'],
            columns = ['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [146]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [147]:
data[["two", "one"]]

          two  one
Ohio        1    0
Colorado    5    4
Utah        9    8
New York   13   12

In [148]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [149]:
data < 5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [151]:
data[data < 5] = 0

In [152]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* loc, iloc 선택하기

In [153]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [155]:
data.loc["Colorado"]["one"]

0

In [157]:
data.loc["Colorado"][["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [158]:
data.loc["Colorado",["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [160]:
data.iloc[1]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [161]:
data.iloc[1][[1, 2]]

two      5
three    6
Name: Colorado, dtype: int64

In [162]:
data.iloc[1,[1, 2]]

two      5
three    6
Name: Colorado, dtype: int64

In [163]:
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [164]:
data.loc[:"Utah"]

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11

In [165]:
data.iloc[:3]

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11

### 실습

* 행삭제

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 삭제

In [ ]:
# '서준', '우현' 행 삭제

* 열삭제

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 삭제

In [ ]:
# '수학', '영어' 열 삭제

*  행선택

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준' 행 선택 (라벨 색인, 정수 색인)

In [ ]:
# '서준', '우현' 행 선택(라벨 색인, 정수 색인, 슬라이싱)

* 열선택

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '수학' 열 선택

In [ ]:
# '음악', '체육' 열 선택

* 원소 선택

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준'의 '음악' 점수

In [ ]:
#'서준'의 '음악','체육' 점수

In [ ]:
#'서준','우현'의 '음악','체육' 점수

* 열추가

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '국어' 열 추가, 값은 80 점 지정

* 행추가

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# "본인 이름" 으로 행추가, 과목 점수도 지정

* 원소값 변경

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# '서준'의 '체육' 점수를 80 점으로 변경(라벨 색인, 정수 색인)

In [ ]:
# '서준'의 '음악','체육' 점수 변경

* 행, 열 바꾸기

In [ ]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [ ]:
# 과목이 행, 학생이 열

* 특정 열을 행 인덱스로 설정

In [ ]:
exam_data = {'이름' : [ '서준', '우현', '인아'],
             '수학' : [ 90, 80, 70],
             '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100],
             '체육' : [ 100, 90, 90]}
df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [ ]:
# '이름' 열을 행 인덱스로 시정

In [ ]:
# reindex 해보기

In [ ]:
# reset_index 해보기

### 실습
- 데이터프레임 객체에서 색인 연습

![image.png]()

In [ ]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five'])
frame2

In [ ]:
# 1

In [ ]:
# 2

In [ ]:
# 3

In [ ]:
# 4

In [ ]:
# 5

In [ ]:
# 6

In [ ]:
# 7